# Generated by Django 4.0 on 2022-01-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
