# Generated by Django 4.0 on 2022-01-16 22:27

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_recipe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=main_app.models.recipe_image_file_path),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.IntegerField(),
        ),
    ]
